In [2]:
str3 = "teststring"

In [3]:
#function to capitalise
#useful for consistency
str3.upper()

'TESTSTRING'

In [4]:
str3.lower()

'teststring'

In [11]:
str3.strip('g')
#does not work on letters that are not at the start/end of string! so only works on t and g in this case

'teststrin'

In [12]:
str4 = "Hello World"

In [13]:
str4.split(' ')

['Hello', 'World']

In [16]:
str4.split('l')

['He', '', 'o Wor', 'd']

In [17]:
# split can be used to change csv into lists!

In [20]:
'-'.join(str4.split(' '))

'Hello-World'

In [21]:
import numpy as np

In [22]:
np.float128(9)

9.0

In [32]:
#there are only 256 digits in unsigned integer (8-bit)
print(np.uint8(255))
print(np.uint8(256))

255
0


In [43]:
my_array_1 = np.array([0, 1, 2, 3, ])

In [44]:
my_array_2 = np.array(my_array_1[:2])
my_array_2

array([0, 1])

In [45]:
my_array_2 + 2

array([2, 3])

In [46]:
my_array_2 * 2

array([0, 2])

In [51]:
np.random.seed(12)
my_array_3 = np.random.randn(10)
my_array_3

array([ 0.47298583, -0.68142588,  0.2424395 , -1.70073563,  0.75314283,
       -1.53472134,  0.00512708, -0.12022767, -0.80698188,  2.87181939])

In [52]:
my_array_3[2]

0.24243949669047796

In [53]:
my_array_3[:3]

array([ 0.47298583, -0.68142588,  0.2424395 ])

In [54]:
my_array_3[-2:]

array([-0.80698188,  2.87181939])

In [56]:
my_array_3[-1::-1]
# first entry:last entry:stride(?)

array([ 2.87181939, -0.80698188, -0.12022767,  0.00512708, -1.53472134,
        0.75314283, -1.70073563,  0.2424395 , -0.68142588,  0.47298583])

In [57]:
my_array_3[0:9:2]

array([ 0.47298583,  0.2424395 ,  0.75314283,  0.00512708, -0.80698188])

In [58]:
exlist = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
exarray = np.array(exlist)

In [59]:
exarray

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [81]:
exarray[1:10:2]

array([ 2,  4,  6,  8, 10])

In [82]:
exarray[-1::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [84]:
exarray * 2 + 1


array([ 3,  5,  7,  9, 11, 13, 15, 17, 19, 21])

In [91]:
# correct solution
tmp = np.arange(1, 10)

In [90]:
tmp[tmp % 2 == 0][::-1] + 1

array([11,  9,  7,  5,  3])